export const GET_REPOSITORIES = "GET_REPOSITORIES";
export const GET_COMMITS = "GET_COMMITS";
export const REFERSH_COMMITS ="REFERSH_COMMITS";
export const SEARCH_COMMITS ="SEARCH_COMMITS";
export const NO_ITEMS_AVAILABLE ="NO_ITEMS_AVAILABLE";
